# Generated by Django 4.1.5 on 2023-01-23 02:38

import credentials.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credential_for', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', credentials.models.PasswordField(editable=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
