# Generated by Django 4.1.5 on 2023-01-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_credential_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
