# Generated by Django 4.1.5 on 2023-01-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_credential_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['credential_for']},
        ),
        migrations.AddField(
            model_name='credential',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credential',
            name='url',
            field=models.CharField(blank=True, max_length=1250, null=True),
        ),
    ]
