# Generated by Django 4.1.5 on 2023-01-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_alter_credential_options_credential_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='credential',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
