# Generated by Django 4.1.5 on 2023-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_remove_credential_is_deleted_credential_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
