# Generated by Django 4.1.5 on 2023-01-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_credential_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='featured_image',
            field=models.ImageField(blank=True, default='accounts/default.jpg', null=True, upload_to='accounts/'),
        ),
    ]
