# Generated by Django 4.1.5 on 2023-01-30 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('credentials', '0007_alter_credential_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
